## reshape

In [2]:
import numpy as np
a = np.arange(9)
b = a.reshape((1, 9))
c = a.reshape((9, 1))
print(f"a: {a.shape}\n {a}\n")
print(f"b: {b.shape}\n {b}")
print(f"c: {c.shape}\n {c}")

a: (9,)
 [0 1 2 3 4 5 6 7 8]

b: (1, 9)
 [[0 1 2 3 4 5 6 7 8]]
c: (9, 1)
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [3]:
import numpy as np
a = np.arange(9)
b = a.reshape((1, -1))
c = a.reshape((-1, 1))
print(f"a: {a.shape}\n {a}\n")
print(f"b: {b.shape}\n {b}")
print(f"c: {c.shape}\n {c}")

a: (9,)
 [0 1 2 3 4 5 6 7 8]

b: (1, 9)
 [[0 1 2 3 4 5 6 7 8]]
c: (9, 1)
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [4]:
import numpy as np
a = np.arange(9)
b = a.reshape((1, 1, 9))
c = a.reshape((1, 9, 1))
d = a.reshape((9, 1, 1))
print(f"a: {a.shape}\n {a}\n")
print(f"b: {b.shape}\n {b}")
print(f"c: {c.shape}\n {c}")
print(f"d: {d.shape}\n {d}")


a: (9,)
 [0 1 2 3 4 5 6 7 8]

b: (1, 1, 9)
 [[[0 1 2 3 4 5 6 7 8]]]
c: (1, 9, 1)
 [[[0]
  [1]
  [2]
  [3]
  [4]
  [5]
  [6]
  [7]
  [8]]]
d: (9, 1, 1)
 [[[0]]

 [[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]

 [[7]]

 [[8]]]


In [7]:
import numpy as np
a = np.random.normal(size=(100, 200))
b = a.reshape((1, 100, 200))
c = a.reshape((100, 200, 1))
print(b.shape)
print(c.shape)

(1, 100, 200)
(100, 200, 1)


#### tuple unpacking

In [11]:
a = (10, 20)
print(*a) 

import numpy as np
a = np.random.normal(size=(100, 150))

print(a.shape)
print(*a.shape)
print((1, *a.shape))
print((*a.shape, 1))

10 20
(100, 150)
100 150
(1, 100, 150)
(100, 150, 1)


In [12]:
import numpy as np
a = np.random.normal(size=(100, 200))
b = a.reshape((1, *a.shape))
c = a.reshape((*a.shape, 1))
print(f"a.shape: {a.shape}\n")
print(f"b.shape: {b.shape}")
print(f"c.shape: {c.shape}")


a.shape: (100, 200)

b.shape: (1, 100, 200)
c.shape: (100, 200, 1)


## slincing 를 이용한 reshape

In [14]:
import numpy as np
a = np.arange(9)

row_vec1 = a[np.newaxis, :]
row_vec2 = a[None, :]        #앞에 새로운 차원
col_vec1 = a[:, np.newaxis]
col_vec2 = a[:, None]

print(f"row_vec1.shape: {row_vec1.shape}")
print(f"row_vec2.shape: {row_vec2.shape}\n")
print(f"col_vec1.shape: {col_vec1.shape}")
print(f"col_vec2.shape: {col_vec2.shape}")


row_vec1.shape: (1, 9)
row_vec2.shape: (1, 9)

col_vec1.shape: (9, 1)
col_vec2.shape: (9, 1)


In [15]:
import numpy as np
# 3차원일때
a = np.arange(9)
b = a[np.newaxis, np.newaxis, :]
c = a[np.newaxis, :, np.newaxis]
d = a[:, np.newaxis, np.newaxis]
print(f"a.shape: {a.shape}\n")
print(f"b.shape: {b.shape}")
print(f"c.shape: {c.shape}")
print(f"d.shape: {d.shape}")

a.shape: (9,)

b.shape: (1, 1, 9)
c.shape: (1, 9, 1)
d.shape: (9, 1, 1)


In [16]:
import numpy as np
# 뒤에 귀찮으닌깐 ... 만붙여서
a = np.random.normal(size=(100, 200))
b = a[np.newaxis, ...]
c = a[..., np.newaxis]

print(f"a.shape: {a.shape}\n")
print(f"b.shape: {b.shape}")
print(f"c.shape: {c.shape}")


a.shape: (100, 200)

b.shape: (1, 100, 200)
c.shape: (100, 200, 1)


#### Using expand_dims API

In [17]:
import numpy as np
a = np.arange(9)
b = np.expand_dims(a, axis=0)
c = np.expand_dims(a, axis=1)
print(f"a.shape: {a.shape}\n")
print(f"b.shape: {b.shape}")
print(f"c.shape: {c.shape}")


a.shape: (9,)

b.shape: (1, 9)
c.shape: (9, 1)


In [18]:
import numpy as np
a = np.arange(9)
b = np.expand_dims(a, axis=(0, 1))
c = np.expand_dims(a, axis=(0, 2))
d = np.expand_dims(a, axis=(1, 2))
print(f"a.shape: {a.shape}\n")
print(f"b.shape: {b.shape}")
print(f"c.shape: {c.shape}")
print(f"d.shape: {d.shape}")


a.shape: (9,)

b.shape: (1, 1, 9)
c.shape: (1, 9, 1)
d.shape: (9, 1, 1)


In [19]:
import numpy as np
a = np.arange(9).reshape((3, 3))
b = np.expand_dims(a, axis=0)
c = np.expand_dims(a, axis=1)
d = np.expand_dims(a, axis=-1)
e = np.expand_dims(a, axis=(0, -1))
print(f"a.shape: {a.shape}\n")
print(f"b.shape: {b.shape}")
print(f"c.shape: {c.shape}")
print(f"d.shape: {d.shape}")
print(f"e.shape: {e.shape}")


a.shape: (3, 3)

b.shape: (1, 3, 3)
c.shape: (3, 1, 3)
d.shape: (3, 3, 1)
e.shape: (1, 3, 3, 1)


In [20]:
import numpy as np
a = np.arange(9).reshape((3, 3))
b = np.expand_dims(a, axis=0)
c = np.expand_dims(a, axis=1)
d = np.expand_dims(a, axis=-1)
e = np.expand_dims(a, axis=(0, -1))
print(f"a.shape: {a.shape}\n")
print(f"b.shape: {b.shape}")
print(f"c.shape: {c.shape}")
print(f"d.shape: {d.shape}")
print(f"e.shape: {e.shape}")


a.shape: (3, 3)

b.shape: (1, 3, 3)
c.shape: (3, 1, 3)
d.shape: (3, 3, 1)
e.shape: (1, 3, 3, 1)
