## np.hstack 
## np.vstack

In [1]:
import numpy as np
a = np.random.randint(0, 10, (4, ))
b = np.random.randint(0, 10, (4, ))
print(f"a: {a.shape}\n{a}")
print(f"b: {b.shape}\n{b}\n")

vstack = np.vstack([a, b])
hstack = np.hstack([a, b])
print(f"vstack: {vstack.shape}\n{vstack}")
print(f"hstack: {hstack.shape}\n{hstack}")

a: (4,)
[4 1 1 0]
b: (4,)
[5 0 1 9]

vstack: (2, 4)
[[4 1 1 0]
 [5 0 1 9]]
hstack: (8,)
[4 1 1 0 5 0 1 9]


In [2]:
import numpy as np
a = np.random.randint(0, 10, (1, 3))
b = np.random.randint(0, 10, (1, 3))
print(f"a: {a.shape}\n{a}")
print(f"b: {b.shape}\n{b}\n")

vstack = np.vstack((a, b))
hstack = np.hstack((a, b))
print(f"vstack: {vstack.shape}\n{vstack}")
print(f"hstack: {hstack.shape}\n{hstack}")

a: (1, 3)
[[5 0 9]]
b: (1, 3)
[[0 6 8]]

vstack: (2, 3)
[[5 0 9]
 [0 6 8]]
hstack: (1, 6)
[[5 0 9 0 6 8]]


#### 열로 계속 쌓고 싶으면 매트릭스 형태로 만들어 줘야함

In [5]:
import numpy as np
a = np.random.randint(0, 10, (3, 1))   # 3,1은 매트릭스의 형태
b = np.random.randint(0, 10, (3, 1))
print(f"a: {a.shape}\n{a}")
print(f"b: {b.shape}\n{b}\n")

vstack = np.vstack((a, b))
hstack = np.hstack((a, b))
print(f"vstack: {vstack.shape}\n{vstack}")
print(f"hstack: {hstack.shape}\n{hstack}")

a: (3, 1)
[[1]
 [5]
 [4]]
b: (3, 1)
[[6]
 [9]
 [4]]

vstack: (6, 1)
[[1]
 [5]
 [4]
 [6]
 [9]
 [4]]
hstack: (3, 2)
[[1 6]
 [5 9]
 [4 4]]


In [9]:
import numpy as np

dataset = np.empty((4, 0))
print(dataset,"\n")
print(f"initial shape: {dataset.shape}\n")

for iter in range(5):
 data_sample = np.random.uniform(0, 5, (4, 1))
 dataset = np.hstack((dataset, data_sample))
 print(f"iter/shape: {iter}/{dataset.shape}")
print(dataset)

[] 

initial shape: (4, 0)

iter/shape: 0/(4, 1)
iter/shape: 1/(4, 2)
iter/shape: 2/(4, 3)
iter/shape: 3/(4, 4)
iter/shape: 4/(4, 5)
[[0.40025618 3.65710198 3.94579682 0.77776518 2.10613785]
 [0.41717278 1.86317397 4.92651397 3.73120005 2.88121359]
 [2.08649328 4.82296918 3.0957206  1.63743716 0.74514278]
 [4.84820136 0.63528519 1.20916671 2.90215017 3.6688356 ]]


In [10]:
import numpy as np
a = np.random.randint(0, 10, (1, 4))
b = np.random.randint(0, 10, (1, 4))
c = np.random.randint(0, 10, (1, 4))

arr_list = [a, b, c]
vstack = np.vstack(arr_list)


print(f"a: {a.shape}\n{a}")
print(f"b: {b.shape}\n{b}")
print(f"c: {c.shape}\n{c}\n")
print(f"vstack: {vstack.shape}\n{vstack}")

a: (1, 4)
[[2 0 6 0]]
b: (1, 4)
[[1 7 5 4]]
c: (1, 4)
[[7 2 4 2]]

vstack: (3, 4)
[[2 0 6 0]
 [1 7 5 4]
 [7 2 4 2]]


In [15]:
import numpy as np
dataset_tmp = list()
for iter in range(5):
 data_sample = np.random.uniform(0, 5, (1, 4))
 dataset_tmp.append(data_sample)
dataset = np.vstack(dataset_tmp)
print(f"final shape: {dataset.shape}","\n")
print(dataset_tmp,"\n")
print(dataset)

final shape: (5, 4) 

[array([[0.58649644, 1.32640551, 3.42655068, 3.80594075]]), array([[0.28907792, 2.32572935, 4.38291137, 4.53754518]]), array([[3.78483492, 2.40455048, 4.89649814, 4.52780665]]), array([[1.89498549, 3.59163785, 0.57564122, 0.60889416]]), array([[3.66475499, 1.53776157, 3.10867765, 2.8032529 ]])] 

[[0.58649644 1.32640551 3.42655068 3.80594075]
 [0.28907792 2.32572935 4.38291137 4.53754518]
 [3.78483492 2.40455048 4.89649814 4.52780665]
 [1.89498549 3.59163785 0.57564122 0.60889416]
 [3.66475499 1.53776157 3.10867765 2.8032529 ]]


### concatenate

In [16]:
import numpy as np
a = np.random.randint(0, 10, (1, 3))
b = np.random.randint(0, 10, (1, 3))
axis0 = np.concatenate([a, b], axis=0)
axis1 = np.concatenate([a, b], axis=1)
axis_n1 = np.concatenate([a, b], axis=-1)

print(f"a: {a.shape}\n{a}")
print(f"b: {b.shape}\n{b}\n")
print(f"axis0: {axis0.shape}\n{axis0}")
print(f"axis1: {axis1.shape}\n{axis1}")
print(f"axis_n1: {axis_n1.shape}\n{axis_n1}")


a: (1, 3)
[[6 5 5]]
b: (1, 3)
[[2 2 4]]

axis0: (2, 3)
[[6 5 5]
 [2 2 4]]
axis1: (1, 6)
[[6 5 5 2 2 4]]
axis_n1: (1, 6)
[[6 5 5 2 2 4]]


In [18]:
import numpy as np
a = np.random.randint(0, 10, (3, 4))
b = np.random.randint(0, 10, (3, 2)) 
concat = np.concatenate([a, b], axis=1)
print(f"a: {a.shape}\n{a}")
print(f"b: {b.shape}\n{b}\n")
print(f"concat: {concat.shape}\n{concat}")


a: (3, 4)
[[7 2 1 0]
 [7 1 1 3]
 [9 3 7 1]]
b: (3, 2)
[[2 7]
 [0 1]
 [6 3]]

concat: (3, 6)
[[7 2 1 0 2 7]
 [7 1 1 3 0 1]
 [9 3 7 1 6 3]]


In [24]:
import numpy as np
a = np.random.randint(0, 10, (3, 4, 5))
print(a)

b = np.random.randint(0, 10, (10, 4, 5))
concat0 = np.concatenate([a, b], axis=0)
print(f"concat0: {concat0.shape}")

b = np.random.randint(0, 10, (3, 10, 5))
concat1 = np.concatenate([a, b], axis=1)
print(f"concat1: {concat1.shape}")

b= np.random.randint(0,10,(3,4,10))
concat2 = np.concatenate([a, b], axis=2)
print(f"concat2: {concat2.shape}")

[[[9 9 2 1 2]
  [9 6 1 7 5]
  [4 2 2 3 8]
  [9 2 2 8 9]]

 [[4 4 4 5 7]
  [5 6 7 0 3]
  [0 3 6 4 1]
  [5 7 4 2 5]]

 [[5 6 8 4 8]
  [1 3 5 4 1]
  [8 8 2 2 1]
  [3 1 3 2 9]]]
concat0: (13, 4, 5)
concat1: (3, 14, 5)
concat2: (3, 4, 15)


In [27]:
import numpy as np

dataset_tmp = list()
for iter in range(100):
 data_sample = np.random.uniform(0, 5, (1, 4))
 dataset_tmp.append(data_sample)
concat = np.concatenate(dataset_tmp, axis=0)
print(f"concat: {concat.shape}")

dataset_tmp = list()
for iter in range(100):
 data_sample = np.random.uniform(0, 5, (4, 1))
 dataset_tmp.append(data_sample)
concat = np.concatenate(dataset_tmp, axis=1)
print(f"concat: {concat.shape}")


concat: (100, 4)
concat: (4, 100)


In [35]:

R = np.random.randint(0, 10, (2, 2))
print(R)
G = np.random.randint(0, 10, size=R.shape)
print(G)
B = np.random.randint(0, 10, size=R.shape)
print(B,"\n")
image = np.dstack([R, G, B])
print(image.shape)
print(image)

[[6 9]
 [4 1]]
[[3 7]
 [3 9]]
[[1 9]
 [0 8]] 

(2, 2, 3)
[[[6 3 1]
  [9 7 9]]

 [[4 3 0]
  [1 9 8]]]


### 조금 더 general 하게 사용 가능 (고차원 텐서에서)

In [37]:
import numpy as np
a = np.random.randint(0, 10, (100, 200, 300))
b = np.random.randint(0, 10, (100, 200, 300))
c = np.random.randint(0, 10, (100, 200, 300))

print("axis=0:", np.stack([a, b, c], axis=0).shape)
print("axis=1:", np.stack([a, b, c], axis=1).shape)
print("axis=2:", np.stack([a, b, c], axis=2).shape)
print("axis=3:", np.stack([a, b, c], axis=3).shape)


axis=0: (3, 100, 200, 300)
axis=1: (100, 3, 200, 300)
axis=2: (100, 200, 3, 300)
axis=3: (100, 200, 300, 3)
