## Rounding and Sorting

In [2]:
import numpy as np
x = np.random.uniform(-5, 5, (5, ))
trunc_where = np.where(x >= 0, np.floor(x), np.ceil(x))
trunc = np.trunc(x)
print(f"x: \n {x}\n")
print(f"trunc_where: \n {trunc_where}")
print(f"trunc: \n{trunc}")

x: 
 [-0.74930673  3.92609783  0.0099435  -1.32260965 -1.7947929 ]

trunc_where: 
 [-0.  3.  0. -1. -1.]
trunc: 
[-0.  3.  0. -1. -1.]


In [3]:
import numpy as np
x = np.random.uniform(-5, 5, (5, ))

print(f"x: \n {x}\n")
print(f"trunc: \n {trunc}")


x: 
 [-0.31873443 -1.01642306 -4.42445439 -2.29141813  1.50781278]

trunc: 
 [-0.  3.  0. -1. -1.]


#### Sorting

In [5]:
import numpy as np
pred = np.random.uniform(0, 100, (5, ))
pred /= pred.sum()
top3_pred = np.sort(pred)[::-1][:3]
top3_indices = np.argsort(pred)[::-1][:3]

print(f"pred: \n{pred.round(3)}\n")
print(f"top-3 pred: {top3_pred.round(3)}")
print(f"top-3 indices: {top3_indices}")

pred: 
[0.037 0.227 0.25  0.246 0.239]

top-3 pred: [0.25  0.246 0.239]
top-3 indices: [2 3 4]


In [6]:
import numpy as np
x = np.random.randint(0, 100, (4, 5))
sort = np.sort(x, axis=0)
argsort = np.argsort(x, axis=0)
print(f"x: \n{x}\n")
print(f"argsort: \n{argsort}")

x: 
[[60 54 14 66 26]
 [ 7 41 63 28 58]
 [13 40 59 71 33]
 [47 23  8 86 93]]

argsort: 
[[1 3 3 1 0]
 [2 2 0 0 2]
 [3 1 2 2 1]
 [0 0 1 3 3]]


In [7]:
import numpy as np
x = np.random.randint(0, 100, (4, 5))

sort = np.sort(x, axis=0)[::-1, :]
argsort = np.argsort(x, axis=0)[::-1, :]
print(f"x: \n{x}\n")
print(f"sort: \n{sort}")
print(f"argsort: \n{argsort}")

x: 
[[18 44 35 31 33]
 [68 42 12 32 60]
 [89 97 53 11 44]
 [26 93 52  2 97]]

sort: 
[[89 97 53 32 97]
 [68 93 52 31 60]
 [26 44 35 11 44]
 [18 42 12  2 33]]
argsort: 
[[2 2 2 1 3]
 [1 3 3 0 1]
 [3 0 0 2 2]
 [0 1 1 3 0]]


In [8]:
import numpy as np
scores = np.random.randint(0, 100, (5, 3))
sort = np.sort(scores, axis=0)[::-1, :]
argsort = np.argsort(scores, axis=0)[::-1, :]
top2_scores = sort[:2, :]
top2_students = argsort[:2, :]
print(f"scores: \n{scores}\n")
print(f"sort: \n{sort}")
print(f"argsort: \n{argsort}\n")
print(f"top-2 scores: \n{top2_scores}")
print(f"top-2 students: \n{top2_students}")

scores: 
[[ 1 59 80]
 [42 92 63]
 [40 83 59]
 [84 19 33]
 [50 27 23]]

sort: 
[[84 92 80]
 [50 83 63]
 [42 59 59]
 [40 27 33]
 [ 1 19 23]]
argsort: 
[[3 1 0]
 [4 2 1]
 [1 0 2]
 [2 4 3]
 [0 3 4]]

top-2 scores: 
[[84 92 80]
 [50 83 63]]
top-2 students: 
[[3 1 0]
 [4 2 1]]


In [9]:
import numpy as np
x = np.random.randint(0, 100, (4, 5))
sort_ascending = np.sort(x, axis=1)
argsort_ascending = np.argsort(x, axis=1)
sort_descending = np.sort(x, axis=1)[:, ::-1]
argsort_descending = np.argsort(x, axis=1)[:, ::-1]
print(f"x: \n{x}\n")
print(f"sort(ascending): \n{sort_ascending}")
print(f"argsort(ascending): \n{argsort_ascending}\n")
print(f"sort(descending): \n{sort_descending}")
print(f"argsort(descending): \n{argsort_descending}\n")

x: 
[[99 10 45 92 48]
 [39  7 27 40 28]
 [19 37 85  6 18]
 [49 31 31 17 42]]

sort(ascending): 
[[10 45 48 92 99]
 [ 7 27 28 39 40]
 [ 6 18 19 37 85]
 [17 31 31 42 49]]
argsort(ascending): 
[[1 2 4 3 0]
 [1 2 4 0 3]
 [3 4 0 1 2]
 [3 1 2 4 0]]

sort(descending): 
[[99 92 48 45 10]
 [40 39 28 27  7]
 [85 37 19 18  6]
 [49 42 31 31 17]]
argsort(descending): 
[[0 3 4 2 1]
 [3 0 4 2 1]
 [2 1 0 4 3]
 [0 4 2 1 3]]



In [10]:
import numpy as np
scores = np.random.randint(0, 100, (5, 3))
sort = np.sort(scores, axis=1)
argsort = np.argsort(scores, axis=1)
bottom2_scores = sort[:, :2]
bottom2_subjects = argsort[:, :2]
print(f"scores: \n{scores}\n")
print(f"sort: \n{sort}")
print(f"argsort: \n{argsort}\n")
print(f"bottom-2 scores: \n{bottom2_scores}")
print(f"bottom-2 subjects: \n{bottom2_subjects}")

scores: 
[[16 11 68]
 [72 91 25]
 [30 19 30]
 [92 86 40]
 [52 52 88]]

sort: 
[[11 16 68]
 [25 72 91]
 [19 30 30]
 [40 86 92]
 [52 52 88]]
argsort: 
[[1 0 2]
 [2 0 1]
 [1 0 2]
 [2 1 0]
 [0 1 2]]

bottom-2 scores: 
[[11 16]
 [25 72]
 [19 30]
 [40 86]
 [52 52]]
bottom-2 subjects: 
[[1 0]
 [2 0]
 [1 0]
 [2 1]
 [0 1]]
