## axis and keepdims augment

In [2]:
import numpy as np
a = np.arange(12).reshape((3, -1))
sum_ = a.sum(axis=0)
print("ndarray: {}\n{}".format(a.shape, a))
print("ndarray.sum(axis=0): {}\n{}".format(sum_.shape, sum_))

ndarray: (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
ndarray.sum(axis=0): (4,)
[12 15 18 21]


In [3]:
import numpy as np
a = np.arange(12).reshape((3, -1))
sum_ = a.sum(axis=1)
print("ndarray: {}\n{}".format(a.shape, a))
print("ndarray.sum(axis=1): {}\n{}".format(sum_.shape, sum_))

ndarray: (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
ndarray.sum(axis=1): (3,)
[ 6 22 38]


#### 브로드캐스팅을 하려면 예를들어 (3,) ---> (3,1)로 변경해줘야 함.    -----> keepdims 사용
#### 하지만 axis를 통해 나온 값들은 대부분(3,) 임

In [4]:
import numpy as np
a = np.arange(12).reshape((3, -1))
sum_class = np.sum(a, axis=0)
sum_student = np.sum(a, axis=1)

print("scores: {}\n{}".format(a.shape, a))
print("sum_class: {}\n{}".format(sum_class.shape,sum_class))
print("sum_student: {}\n{}".format(sum_student.shape,sum_student))

scores: (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
sum_class: (4,)
[12 15 18 21]
sum_student: (3,)
[ 6 22 38]


### keepdims 사용 ---> 브로드캐스팅을 위해서

In [5]:
import numpy as np
a = np.arange(12).reshape((3, -1))
sum_class = np.sum(a, axis=0, keepdims=True)
sum_student = np.sum(a, axis=1, keepdims=True)

print("scores: {}\n{}".format(a.shape, a),"\n")
print("sum_class: {}\n{}".format(sum_class.shape,sum_class),"\n")
print("sum_student: {}\n{}".format(sum_student.shape,sum_student),"\n")

scores: (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

sum_class: (1, 4)
[[12 15 18 21]] 

sum_student: (3, 1)
[[ 6]
 [22]
 [38]] 



In [9]:
import numpy as np
n_student, n_class = 3, 4
m_score, M_score = 0, 100
scores = np.random.randint(low=m_score,high=M_score,size=(n_student,n_class))
mean_class = np.mean(scores, axis=0, keepdims=True)
mean_student = np.mean(scores, axis=1, keepdims=True)

print("Shapes: ","\n")
print(scores.shape, mean_class.shape, mean_student.shape, '\n')
print("scores : ","\n", scores, "\n")
print("Mean subtraction by classes\n", scores - mean_class,"\n")
print("Mean subtraction by students\n", scores - mean_student)

Shapes:  

(3, 4) (1, 4) (3, 1) 

scores :  
 [[64 80  8 11]
 [16 85  2 38]
 [60 31 34  1]] 

Mean subtraction by classes
 [[ 17.33333333  14.66666667  -6.66666667  -5.66666667]
 [-30.66666667  19.66666667 -12.66666667  21.33333333]
 [ 13.33333333 -34.33333333  19.33333333 -15.66666667]] 

Mean subtraction by students
 [[ 23.25  39.25 -32.75 -29.75]
 [-19.25  49.75 -33.25   2.75]
 [ 28.5   -0.5    2.5  -30.5 ]]


In [10]:
import numpy as np
a = np.arange(2*3*4).reshape((2, 3, 4))
sum_ = a.sum(axis=0)
print("ndarray: {}\n{}".format(a.shape, a))
print("ndarray.sum(axis=0): {}\n{}".format(sum_.shape, sum_))

ndarray: (2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
ndarray.sum(axis=0): (3, 4)
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


### keepdims를 적용안했을때와 했을때의 차이

In [13]:
import numpy as np
a = np.arange(2*3*4).reshape((2, 3, 4)) 
sum_ = a.sum(axis=1)
sum_k = a.sum(axis=1, keepdims=True)

print("ndarray: {}\n{}".format(a.shape, a),"\n")
print("axis=1: {}\n{}".format(sum_.shape, sum_),"\n")
print("axis=1, keepdims=True: {}\n{}"\
    .format(sum_k.shape,sum_k))

ndarray: (2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 

axis=1: (2, 4)
[[12 15 18 21]
 [48 51 54 57]] 

axis=1, keepdims=True: (2, 1, 4)
[[[12 15 18 21]]

 [[48 51 54 57]]]


In [14]:
import numpy as np
a = np.arange(2*3*4).reshape((2, 3, 4))
sum_ = a.sum(axis=2)
sum_k = a.sum(axis=2, keepdims=True)
print("ndarray: {}\n{}".format(a.shape, a),"\n")
print("axis=2: {}\n{}".format(sum_.shape, sum_),"\n")
print("axis=2, keepdims=True: {}\n{}"\
 .format(sum_k.shape,sum_k)) 

ndarray: (2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 

axis=2: (2, 3)
[[ 6 22 38]
 [54 70 86]] 

axis=2, keepdims=True: (2, 3, 1)
[[[ 6]
  [22]
  [38]]

 [[54]
  [70]
  [86]]]


### 3차원 텐서 ( 모의고사, 학생, 과목) 
####  axis=0은 학생 * 과목에 대한 평균, axis=1은 모의고사 * 과목에 대한 평균  

In [16]:
import numpy as np
n_test_time, n_student, n_class = 4, 3, 4
m_score, M_score = 0, 100
scores = np.random.randint(low=m_score,high=M_score,size=(n_test_time,n_student,n_class))
print("scores: \n", scores,"\n")

score_mean = np.mean(scores, axis=0)
print("score mean: ",score_mean.shape, '\n',score_mean)
score_mean = np.mean(scores, axis=1)
print("score mean: ",score_mean.shape, '\n',score_mean)

scores: 
 [[[99 52 64 49]
  [69 86 85 92]
  [ 5  5 70 83]]

 [[57 66  0 82]
  [82 49  1 25]
  [94 30  7  8]]

 [[39 76 56 99]
  [57 10 20 88]
  [85 45 86 74]]

 [[33 78 70 82]
  [35 81 37 46]
  [86 41 36 69]]] 

score mean:  (3, 4) 
 [[57.   68.   47.5  78.  ]
 [60.75 56.5  35.75 62.75]
 [67.5  30.25 49.75 58.5 ]]
score mean:  (4, 4) 
 [[57.66666667 47.66666667 73.         74.66666667]
 [77.66666667 48.33333333  2.66666667 38.33333333]
 [60.33333333 43.66666667 54.         87.        ]
 [51.33333333 66.66666667 47.66666667 65.66666667]]


In [17]:
import numpy as np
C, H, W = 3, 100, 200
# (C, H, W) case
images = np.random.randint(0, 256,
 size=(C, H, W))
print("Shape of original image:", images.shape,"\n")

gray_image = np.mean(images, axis=0)
print("Shape of gray-scaled image:", gray_image.shape, '\n')
gray_image = np.mean(images, axis=-1)
print("Shape of gray-scaled image:", gray_image.shape)


Shape of original image: (3, 100, 200) 

Shape of gray-scaled image: (100, 200) 

Shape of gray-scaled image: (3, 100)
