## ndarray의 원소별 연산과 브로드캐스팅

In [1]:
import numpy as np
a = np.random.randint(-5, 5, (5, ))
b = np.random.randint(-5, 5, (5, ))

print("a: ", a)
print("b: ", b, '\n')
print("a + b: ", a + b)

a:  [-3  0 -4 -5 -3]
b:  [-1 -4 -3  0  0] 

a + b:  [-4 -4 -7 -5 -3]


In [2]:
a = np.random.randint(1, 5, (5, ))
b = np.random.randint(1, 5, (5, ))
print("a: ", a)
print("b: ", b, '\n')
print("a + b: ", a + b)
print("a - b: ", a - b)
print("a * b: ", a * b)
print("a / b: ", a / b)
print("a // b: ", a // b)
print("a % b: ", a % b)
print("a ** b: ", a ** b)

a:  [1 4 3 3 2]
b:  [3 2 4 4 4] 

a + b:  [4 6 7 7 6]
a - b:  [-2  2 -1 -1 -2]
a * b:  [ 3  8 12 12  8]
a / b:  [0.33333333 2.         0.75       0.75       0.5       ]
a // b:  [0 2 0 0 0]
a % b:  [1 0 3 3 2]
a ** b:  [ 1 16 81 81 16]


#### masking

In [3]:
a = np.arange(5)

mask = np.array([0, 1, 0, 1, 0])
print("input: ", a)
print("mask: ", mask)
print("output: ", a*b)

input:  [0 1 2 3 4]
mask:  [0 1 0 1 0]
output:  [ 0  2  8 12 16]


In [4]:
a = np.arange(1, 5).reshape((2, 2))
mask = np.array([[0, 0], [1, 0]])
print("input: \n", a)
print("mask: \n", mask)
print("output: \n", a*mask)

input: 
 [[1 2]
 [3 4]]
mask: 
 [[0 0]
 [1 0]]
output: 
 [[0 0]
 [3 0]]


### When ndims Are Equal(Matrices)
#### 2차원 

In [1]:
import numpy as np
A = np.arange(9).reshape(3, 3)
B = 10*np.arange(3).reshape((-1, 3))
C = A + B

print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}\n".format(A.ndim, B.shape, B))
print("A + B: {}/{}\n{}".format(A.ndim, C.shape, C))

A: 2/(3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
B: 2/(1, 3)
[[ 0 10 20]]

A + B: 2/(3, 3)
[[ 0 11 22]
 [ 3 14 25]
 [ 6 17 28]]


In [2]:
import numpy as np
A = np.arange(9).reshape(3, 3)
B = 10*np.arange(3).reshape((3, -1))
C = A + B

print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}\n".format(A.ndim, B.shape, B))
print("A + B: {}/{}\n{}".format(A.ndim, C.shape, C))

A: 2/(3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
B: 2/(3, 1)
[[ 0]
 [10]
 [20]]

A + B: 2/(3, 3)
[[ 0  1  2]
 [13 14 15]
 [26 27 28]]


In [3]:
import numpy as np
A = np.arange(3).reshape((3, -1))
B = 10*np.arange(3).reshape((-1, 3))
C = A + B

print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}\n".format(A.ndim, B.shape, B))
print("A + B: {}/{}\n{}".format(A.ndim, C.shape, C))

A: 2/(3, 1)
[[0]
 [1]
 [2]]
B: 2/(1, 3)
[[ 0 10 20]]

A + B: 2/(3, 3)
[[ 0 10 20]
 [ 1 11 21]
 [ 2 12 22]]


#### 3차원

In [4]:
import numpy as np
A = np.arange(18).reshape((2, 3, 3))
B = 10*np.arange(9).reshape((1, 3, 3))
C = A + B
print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}\n".format(A.ndim, B.shape, B))
print("A + B: {}/{}\n{}".format(A.ndim, C.shape, C))

A: 3/(2, 3, 3)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
B: 3/(1, 3, 3)
[[[ 0 10 20]
  [30 40 50]
  [60 70 80]]]

A + B: 3/(2, 3, 3)
[[[ 0 11 22]
  [33 44 55]
  [66 77 88]]

 [[ 9 20 31]
  [42 53 64]
  [75 86 97]]]


#### When ndims Are Not Equal

In [5]:
import numpy as np
a = np.array(3)
u = np.arange(5)
print("shapes: {}/{}".format(a.shape, u.shape))
print("a: ", a)
print("u: ", u, '\n')
print("a*u: ", a*u)

shapes: ()/(5,)
a:  3
u:  [0 1 2 3 4] 

a*u:  [ 0  3  6  9 12]


In [6]:
import numpy as np
a = np.array(3)
u = np.arange(1, 5)
shapes = "shapes: {}/{}"
print(shapes.format(a.shape,u.shape))
print("a: ", a)
print("u: ", u, '\n')
print("a + u: ", a + u)
print("a - u: ", a - u)
print("a * u: ", a * u)
print("a / u: ", a / u)
print("a // u: ", a // u)
print("a % u: ", a % u)
print("a ** u: ", a ** u,'\n')

print("a >= u: ", a >= u)
print("a < u: ", a < u)
print("a <= u: ", a <= u)
print("a == u: ", a == u)
print("a != u: ", a != u)

shapes: ()/(4,)
a:  3
u:  [1 2 3 4] 

a + u:  [4 5 6 7]
a - u:  [ 2  1  0 -1]
a * u:  [ 3  6  9 12]
a / u:  [3.   1.5  1.   0.75]
a // u:  [3 1 1 0]
a % u:  [0 1 0 3]
a ** u:  [ 3  9 27 81] 

a >= u:  [ True  True  True False]
a < u:  [False False False  True]
a <= u:  [False False  True  True]
a == u:  [False False  True False]
a != u:  [ True  True False  True]


In [7]:
A = np.array([10, 20])
B = np.arange(6).reshape((3, 2))
C = A + B

print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}\n".format(A.ndim, B.shape, B))
print("A + B: {}/{}\n{}".format(A.ndim, C.shape, C))

A: 1/(2,)
[10 20]
B: 1/(3, 2)
[[0 1]
 [2 3]
 [4 5]]

A + B: 1/(3, 2)
[[10 21]
 [12 23]
 [14 25]]


In [8]:
A = np.arange(2*3*4).reshape((2, 3, 4))
B = 10*np.arange(4)
C = A + B
print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}\n".format(A.ndim, B.shape, B))
print("A + B: {}/{}\n{}".format(A.ndim, C.shape, C))

A: 3/(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
B: 3/(4,)
[ 0 10 20 30]

A + B: 3/(2, 3, 4)
[[[ 0 11 22 33]
  [ 4 15 26 37]
  [ 8 19 30 41]]

 [[12 23 34 45]
  [16 27 38 49]
  [20 31 42 53]]]
