## Indexing and Slicing

In [1]:
import numpy as np
a = np.arange(10)
print(f"ndarray: \n{a}\n")
print("a[0] : ", a[0])
print("a[2] : ", a[2])
print("a[-1] : ", a[-1]) # the last element
print("a[-2] : ", a[-2]) # the 2nd last element

ndarray: 
[0 1 2 3 4 5 6 7 8 9]

a[0] :  0
a[2] :  2
a[-1] :  9
a[-2] :  8


In [2]:

print(f"ndarray: \n{a}\n")
print("a[0:3] : ", a[0:3])
print("a[3:7] : ", a[3:7])
print("a[5:-1] : ", a[5:-1])
print(f"ndarray: \n{a}\n")
print("a[2:] : ", a[2:])
print("a[-2:] : ", a[-2:]) # the last two elements
print("a[:5] : ", a[:5])
print("a[:-3] : ", a[:-3])
print("a[:] : ", a[:])

ndarray: 
[0 1 2 3 4 5 6 7 8 9]

a[0:3] :  [0 1 2]
a[3:7] :  [3 4 5 6]
a[5:-1] :  [5 6 7 8]
ndarray: 
[0 1 2 3 4 5 6 7 8 9]

a[2:] :  [2 3 4 5 6 7 8 9]
a[-2:] :  [8 9]
a[:5] :  [0 1 2 3 4]
a[:-3] :  [0 1 2 3 4 5 6]
a[:] :  [0 1 2 3 4 5 6 7 8 9]


#### [start : end : stop]

In [3]:
import numpy as np
a = np.arange(10)
print(f"ndarray: \n{a}\n")
print("a[2:7:2] : ", a[2:7:2])
print("a[::3] : ", a[::3])

ndarray: 
[0 1 2 3 4 5 6 7 8 9]

a[2:7:2] :  [2 4 6]
a[::3] :  [0 3 6 9]


In [4]:
a = np.arange(10)
print(f"ndarray: \n{a}\n")
print("a[7:2:-1] : ", a[7:2:-1])
print("a[::-1] : ", a[::-1])
print("a[8:3:-2] : ", a[8:3:-2])
print("a[::-3] : ", a[::-3])

ndarray: 
[0 1 2 3 4 5 6 7 8 9]

a[7:2:-1] :  [7 6 5 4 3]
a[::-1] :  [9 8 7 6 5 4 3 2 1 0]
a[8:3:-2] :  [8 6 4]
a[::-3] :  [9 6 3 0]


In [5]:
import numpy as np
a = np.arange(10)
indices = np.array([0, 3, 6, -1])

print(f"ndarray: \n{a}\n")
print(a[[0, 3, 6, -1]])
print(a[indices])
print(a[a%3==0])

ndarray: 
[0 1 2 3 4 5 6 7 8 9]

[0 3 6 9]
[0 3 6 9]
[0 3 6 9]


#### list 와 numnpy 비교
##### numpy 효율성

In [7]:
a = list(range(1, 11))
print(a)

for data_idx in range(5):
 a[data_idx] = 0
print(a)


a = np.arange(1, 11)
print(a)

a[:5] = 0
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[0, 0, 0, 0, 0, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 0  0  0  0  0  6  7  8  9 10]


In [8]:
a = np.arange(1, 11)
print(a)

a[::2] = 200
print(a)

a[5:-1:3] = 300
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[200   2 200   4 200   6 200   8 200  10]
[200   2 200   4 200 300 200   8 300  10]


In [10]:
a = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
a = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]

print(a[0])
print(a[1])
print(a[2])


[0, 1, 2]
[3, 4, 5]
[6, 7, 8]


In [9]:
a = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
print(a[0][0], a[0][1], a[0][2])
print(a[1][0], a[1][1], a[0][2])
print(a[2][0], a[2][1], a[2][2])

0 1 2
3 4 2
6 7 8


In [11]:
import numpy as np
a = np.arange(9).reshape((3, 3))
print(f"ndarray: \n{a}\n")
print(a[0, 0], a[0, 1], a[0, 2])
print(a[1, 0], a[1, 1], a[1, 2])
print(a[2, 0], a[2, 1], a[2, 2])

ndarray: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

0 1 2
3 4 5
6 7 8


In [12]:
import numpy as np
a = np.arange(9).reshape((3, 3))
print(f"ndarray: \n{a}\n")
print(a[0][0], a[0][1], a[0][2])
print(a[1][0], a[1][1], a[1][2])
print(a[2][0], a[2][1], a[2][2])

ndarray: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

0 1 2
3 4 5
6 7 8


#### 행별 뽑아내기

In [13]:
import numpy as np
a = np.arange(12).reshape((3, 4))
print(f"ndarray: \n{a}\n")
print("a[0, 1:] : ", a[0, 1:])
print("a[1, :3] : ", a[1, :3])
print("a[2, 1:3] : ", a[2, 1:3])

ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

a[0, 1:] :  [1 2 3]
a[1, :3] :  [4 5 6]
a[2, 1:3] :  [ 9 10]


#### 열별 뽑아내기

In [14]:
import numpy as np
a = np.arange(12).reshape((4, 3))
print(f"ndarray: \n{a}\n")
print("a[1:, 0] : ", a[1:, 0])
print("a[:3, 1] : ", a[:3, 1])
print("a[1:3, 2] : ", a[1:3, 2])

ndarray: 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

a[1:, 0] :  [3 6 9]
a[:3, 1] :  [1 4 7]
a[1:3, 2] :  [5 8]


In [15]:
import numpy as np
a = np.arange(16).reshape((4, 4))
print(f"ndarray: \n{a}\n")
print("a[1:3, 1:3] : \n", a[1:3, 1:3])
print("a[:2, :3] : \n", a[:2, :3])
print("a[1:, 2:] : \n", a[1:, 2:])
print("a[2:, :-2] : \n", a[2:, :-2])

ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

a[1:3, 1:3] : 
 [[ 5  6]
 [ 9 10]]
a[:2, :3] : 
 [[0 1 2]
 [4 5 6]]
a[1:, 2:] : 
 [[ 6  7]
 [10 11]
 [14 15]]
a[2:, :-2] : 
 [[ 8  9]
 [12 13]]


In [17]:
import numpy as np
image = np.arange(9).reshape((3, 3))
print(f"ndarray: \n{image}\n")

horizontal_flip = image[:, ::-1]  # 행은 그대로 컬럼은 거꾸로
print(f"horizontal_flip: \n{horizontal_flip}\n")

vertical_flip = image[::-1, :] # 행을 거꿀로 컬럼은 그대로
print(f"vertical_flip: \n{vertical_flip}\n")

rotation = image[::-1, ::-1] # 행,열 거꾸로
print(f"rotation: \n{rotation}\n")


ndarray: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

horizontal_flip: 
[[2 1 0]
 [5 4 3]
 [8 7 6]]

vertical_flip: 
[[6 7 8]
 [3 4 5]
 [0 1 2]]

rotation: 
[[8 7 6]
 [5 4 3]
 [2 1 0]]



In [18]:
import numpy as np
a = np.arange(16).reshape((4, 4))
print(f"ndarray: \n{a}\n")

print("a[0, :] : \n", a[0, :])

print("a[0, ...] : \n", a[0, ...]) # 행은 0행 컬럼은 모든차원의 컬럼을 가져와라

print("a[:, 1] : \n", a[:, 1])

print("a[..., 1] : \n", a[..., 1]) # 열은 0열 행은 모든차원의 행을 가져와라


ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

a[0, :] : 
 [0 1 2 3]
a[0, ...] : 
 [0 1 2 3]
a[:, 1] : 
 [ 1  5  9 13]
a[..., 1] : 
 [ 1  5  9 13]


In [19]:
import numpy as np
a = np.arange(3*3*3).reshape((3, 3, 3))
print(f"ndarray: \n{a}\n")
print("a[0, 0] : \n", a[0, 0])
print("a[0, 1] : \n", a[0, 1])
print("a[0, 2] : \n", a[0, 2], '\n')
print("a[1, 0] : \n", a[1, 0])
print("a[1, 1] : \n", a[1, 1])
print("a[1, 2] : \n", a[1, 2], '\n')
print("a[2, 0] : \n", a[2, 0])
print("a[2, 1] : \n", a[2, 1])
print("a[2, 2] : \n", a[2, 2])


ndarray: 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

a[0, 0] : 
 [0 1 2]
a[0, 1] : 
 [3 4 5]
a[0, 2] : 
 [6 7 8] 

a[1, 0] : 
 [ 9 10 11]
a[1, 1] : 
 [12 13 14]
a[1, 2] : 
 [15 16 17] 

a[2, 0] : 
 [18 19 20]
a[2, 1] : 
 [21 22 23]
a[2, 2] : 
 [24 25 26]


In [22]:
a = np.arange(3*3*3).reshape((3, 3, 3))
print(f"ndarray: \n{a}\n")
print("a[0, :2, :2] : \n", a[0, :2, :2])
print("a[1, :2, :] : \n", a[1, :2, :])
print("a[2, -2:, -2:] : \n", a[2, -2:, -2:])

ndarray: 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

a[0, :2, :2] : 
 [[0 1]
 [3 4]]
a[1, :2, :] : 
 [[ 9 10 11]
 [12 13 14]]
a[2, -2:, -2:] : 
 [[22 23]
 [25 26]]


In [23]:
import numpy as np
images = np.random.normal(size=(32, 100, 200))
print("image set: ", images.shape)

col0 = images[:, :, 0]
print(col0.shape)

col0 = images[..., 0]
print(col0.shape, '\n')

image0_col0 = images[0, :, 0]
print(image0_col0.shape)

image0_col0 = images[0, ..., 0]
print(image0_col0.shape)

image set:  (32, 100, 200)
(32, 100)
(32, 100) 

(100,)
(100,)


In [24]:
import numpy as np
#3개의 채널의 0행 1행 모두 가져오기
a = np.arange(3*3*3).reshape((3, 3, 3))
print(f"ndarray: \n{a}\n")
print("a[:, :2, :] : \n", a[:, :2, :])

ndarray: 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

a[:, :2, :] : 
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 9 10 11]
  [12 13 14]]

 [[18 19 20]
  [21 22 23]]]


In [25]:
import numpy as np
# 3개 채널의 1열 다 가져오기
a = np.arange(3*3*3).reshape((3, 3, 3))
print(f"ndarray: \n{a}\n")
print("a[:, :, 0] : \n", a[:, :, 0])

ndarray: 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

a[:, :, 0] : 
 [[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]


In [26]:
import numpy as np
image = np.random.normal(size=(3, 500, 300))
image_r = image[0]
image_g = image[1]
image_b = image[2]
print(image_r.shape, image_g.shape, image_b.shape)


image = np.random.normal(size=(3, 500, 300))
image_r, image_g, image_b = image
print(image_r.shape, image_g.shape, image_b.shape)

(500, 300) (500, 300) (500, 300)
(500, 300) (500, 300) (500, 300)


In [27]:
import numpy as np
image = np.random.normal(size=(3, 500, 300))

top_left = image[:, :100, :100]
top_right = image[:, :100, -100:]
bottom_left = image[:, -100:, :100]
bottom_right = image[:, -100:, -100:]

print(top_left.shape, top_right.shape)
print(bottom_left.shape, bottom_right.shape)

(3, 100, 100) (3, 100, 100)
(3, 100, 100) (3, 100, 100)


In [33]:
image = np.random.normal(size=(3, 3, 2))
print(image,"\n")
top_right = image[:, :2, -1:]
print(top_right)

[[[-0.07536938 -2.46508398]
  [-0.58495699  0.39064909]
  [ 1.18742156 -0.39599743]]

 [[-0.1366251  -0.82000804]
  [-0.73160467  1.74301635]
  [ 0.99970678  0.64040807]]

 [[-0.05577067 -0.01456578]
  [ 0.46842506 -0.88444275]
  [-0.45075463  1.04568253]]] 

[[[-2.46508398]
  [ 0.39064909]]

 [[-0.82000804]
  [ 1.74301635]]

 [[-0.01456578]
  [-0.88444275]]]


In [34]:
import numpy as np
a = np.arange(10)
print(f"ndarray: \n{a}\n")
indices = np.array([[1, 2, 3], [5, 8, 9]])
print(f"indices: \n{indices}")
print(f"a[indices]: \n{a[indices]}")

ndarray: 
[0 1 2 3 4 5 6 7 8 9]

indices: 
[[1 2 3]
 [5 8 9]]
a[indices]: 
[[1 2 3]
 [5 8 9]]


In [35]:
import numpy as np
a = np.random.randint(0, 20, (10, ))
print(f"ndarray: \n{a}\n")

indices = np.random.randint(0, 10, size=(2, 3, 4))
print(f"indices: \n{indices}")
print(f"a[indices]: \n{a[indices]}")

ndarray: 
[11  9 15  7  1  6  1 11 15 18]

indices: 
[[[7 0 6 9]
  [6 2 9 7]
  [6 7 5 3]]

 [[0 4 6 3]
  [6 9 0 9]
  [5 0 8 9]]]
a[indices]: 
[[[11 11  1 18]
  [ 1 15 18 11]
  [ 1 11  6  7]]

 [[11  1  1  7]
  [ 1 18 11 18]
  [ 6 11 15 18]]]


In [36]:
import numpy as np
a = np.arange(12).reshape((3, 4))
print(f"ndarray: \n{a}\n")
print("a[0]: ", a[0])
print("a[1]: ", a[1])
print("a[2]: ", a[2])

ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

a[0]:  [0 1 2 3]
a[1]:  [4 5 6 7]
a[2]:  [ 8  9 10 11]


In [37]:
import numpy as np
a = np.arange(12).reshape((3, 4))
print(f"ndarray: \n{a}\n")

indices = np.array([0, 2])
print(f"indices: \n{indices}")
print(f"a[indices]: \n{a[indices]}")

ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

indices: 
[0 2]
a[indices]: 
[[ 0  1  2  3]
 [ 8  9 10 11]]


In [38]:
import numpy as np
a = np.arange(12).reshape((3, 4))
print(f"ndarray: \n{a}\n")

indices = np.array([0, 0, 1, 1, 2, 2])
print(f"indices: \n{indices}")
print(f"a[indices]: \n{a[indices]}")

ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

indices: 
[0 0 1 1 2 2]
a[indices]: 
[[ 0  1  2  3]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 8  9 10 11]]


##### np.array([0, 0, 1, 1, 2, 2]) 가 6개의 벡터가 만들어짐. 
##### 6개의 벡터 안에 처음 매트릭스의 행부분의 4개의 원소가 들어가짐

In [40]:
import numpy as np

a = np.arange(12).reshape((3, 4))
print(f"ndarray: \n{a}\n")

indices = np.array([[0, 1, 2], [-3, -2, -1]])  # 2 *3 이 만들어지는데 각각의 데이터에 4개의 데이터가 붙음 =>(2,3,4)가 됨.

print(f"indices: \n{indices}")
print(f"a[indices]: \n{a[indices]}")

ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

indices: 
[[ 0  1  2]
 [-3 -2 -1]]
a[indices]: 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


In [41]:
import numpy as np
a = np.arange(12).reshape((3, 4))
print(f"ndarray: \n{a}\n")

indices0, indices1 = np.array([0]), np.array([0])
indices0, indices1 = np.array([1]), np.array([2])
print(a[indices0, indices1]) 
print(a[indices0, indices1])

indices0, indices1 = np.array([-1]), np.array([0])
print(a[indices0, indices1])

indices0, indices1 = np.array([-1]), np.array([-1])
print(a[indices0, indices1])

ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[6]
[6]
[8]
[11]


In [43]:
import numpy as np
a = np.arange(12).reshape((3, 4))
print(f"ndarray: \n{a}\n")

indices0 = np.array([[0, 1, 2], [0, 1, 2]])
indices1 = np.array([[0, 1, 2], [1, 2, 3]])

print("Paired indices")

for row_indices0, row_indices1 in zip(indices0, indices1):
    
    for idx0, idx1 in zip(row_indices0, row_indices1):
        print(f"({idx0}, {idx1})", end=' ')
    print("\n")


print(f"a[indices0, indices1]: \n{a[indices0, indices1]}")


ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Paired indices
(0, 0) (1, 1) (2, 2) 

(0, 1) (1, 2) (2, 3) 

a[indices0, indices1]: 
[[ 0  5 10]
 [ 1  6 11]]


### bool ndarray

In [46]:
import numpy as np
a = np.arange(5)
print(f"ndarray: \n{a}","\n")

b_indices = np.array([True, False, True, False, True])
print(f"b_indices: \n{b_indices}\n")
print(f"a[b_indices]: \n{a[b_indices]}")

ndarray: 
[0 1 2 3 4] 

b_indices: 
[ True False  True False  True]

a[b_indices]: 
[0 2 4]


In [47]:
import numpy as np
a = np.random.randint(0, 20, (10, ))
print(f"ndarray: \n{a}","\n")

b_indices = (a % 2 == 0)
print(f"b_indices: \n{b_indices}\n")
print(f"a[b_indices]: \n{a[b_indices]}")

ndarray: 
[ 9 16 19  7  4 11  3  7  9 15] 

b_indices: 
[False  True False False  True False False False False False]

a[b_indices]: 
[16  4]


In [49]:
import numpy as np
a = np.random.randint(0, 20, (2, 2))
print(f"ndarray: \n{a}","\n")

b_indices = np.array([[True, False],[False, True]])
print(f"b_indices: \n{b_indices}\n")
print(f"a[b_indices]: \n{a[b_indices]}")

ndarray: 
[[ 0  7]
 [18  7]] 

b_indices: 
[[ True False]
 [False  True]]

a[b_indices]: 
[0 7]


In [50]:
import numpy as np
a = np.random.randint(0, 20, (3, 4))
print(f"ndarray: \n{a}","\n")

b_indices = (a > 10)
print(f"b_indices: \n{b_indices}\n")
print(f"a[b_indices]: \n{a[b_indices]}")

ndarray: 
[[15 11 14 12]
 [ 6  4  8 19]
 [ 2  6  4  3]] 

b_indices: 
[[ True  True  True  True]
 [False False False  True]
 [False False False False]]

a[b_indices]: 
[15 11 14 12 19]


In [51]:
import numpy as np


a = np.array([True, False, True, False])
nonzero = np.nonzero(a)
where = np.where(a)

print(f"a: \n{a}\n")
print(f"nonzero: \n{nonzero}")
print(f"where: \n{where}","\n")




a = np.array([[True, False],[True, False]])
nonzero = np.nonzero(a)
where = np.where(a)

print(f"a: \n{a}\n")
print(f"nonzero: \n{nonzero}","\n")
print(f"where: \n{where}")

a: 
[ True False  True False]

nonzero: 
(array([0, 2], dtype=int64),)
where: 
(array([0, 2], dtype=int64),) 

a: 
[[ True False]
 [ True False]]

nonzero: 
(array([0, 1], dtype=int64), array([0, 0], dtype=int64)) 

where: 
(array([0, 1], dtype=int64), array([0, 0], dtype=int64))


In [52]:
import numpy as np
a = np.array([[[True, False, True],
                [True, False, False]],
                [[False, True, False],
                [True, False, True]]])

print(f"a: \n{a}\n")
print(f"nonzero: \n{nonzero}")
print(f"where: \n{where}")

a: 
[[[ True False  True]
  [ True False False]]

 [[False  True False]
  [ True False  True]]]

nonzero: 
(array([0, 1], dtype=int64), array([0, 0], dtype=int64))
where: 
(array([0, 1], dtype=int64), array([0, 0], dtype=int64))


In [56]:
import numpy as np
a = np.random.randint(-2, 3, size=(3, 3))
u_nonzero = a[np.nonzero(a)]
u_where = a[np.where(a)]
u_bool = a[a != 0]

print(f"a: \n{a}\n")
print(f"using nonzero: \n{u_nonzero}")
print(f"using where: \n{u_where}")
print(f"using bool ndarray: \n{u_bool}")

a: 
[[-2 -1  2]
 [-1  0  2]
 [ 2 -1 -1]]

using nonzero: 
[-2 -1  2 -1  2  2 -1 -1]
using where: 
[-2 -1  2 -1  2  2 -1 -1]
using bool ndarray: 
[-2 -1  2 -1  2  2 -1 -1]


In [57]:
import numpy as np
a = np.random.randint(-2, 3, size=(3, 3))

u_nonzero = a[np.nonzero(a > 0)]
u_where = a[np.where(a > 0)]
u_bool = a[a > 0]

print(f"a: \n{a}\n")
print(f"using nonzero: \n{u_nonzero}")
print(f"using where: \n{u_where}")
print(f"using bool ndarray: \n{u_bool}")

a: 
[[ 0 -1 -2]
 [ 0 -2  0]
 [-2  2  2]]

using nonzero: 
[2 2]
using where: 
[2 2]
using bool ndarray: 
[2 2]
