### 넘파이의 합곱차 구하기

In [2]:
import numpy as np
a = np.arange(5)
print("ndarray: ",a)

cumsum = np.cumsum(a)
print("cumsum: ",cumsum)

ndarray:  [0 1 2 3 4]
cumsum:  [ 0  1  3  6 10]


In [4]:
import numpy as np
a = np.arange(3*3).reshape((3, 3))
cumsum = np.cumsum(a)
print("ndarray: {}\n{}".format(a.shape, a))
print("cumsum: {}\n{}".format(cumsum.shape, cumsum))



ndarray: (3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
cumsum: (9,)
[ 0  1  3  6 10 15 21 28 36]


In [6]:
a = np.arange(2*3*4).reshape((2, 3, 4))
cumsum = np.cumsum(a)


print("ndarray: {}\n{}".format(a.shape, a))
print("cumsum: {}\n{}".format(cumsum.shape, cumsum))

ndarray: (2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
cumsum: (24,)
[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153
 171 190 210 231 253 276]


#### 행별 더하기 ---> axis=0

In [11]:
a = np.arange(3*4).reshape((3, 4))
print("ndarray: {}\n{}".format(a.shape, a),"\n")

cumsum = np.cumsum(a, axis=0)
print("cumsum: {}\n{}"\
 .format(cumsum.shape,cumsum))



ndarray: (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

cumsum: (3, 4)
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]


#### 열별 더하기 ---> axis=1

In [12]:
cumsum = np.cumsum(a,axis=1)
print("cunsum: {}\n{}"\
    .format(cumsum.shape,cumsum))

cunsum: (3, 4)
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]
