In [3]:
import numpy as np
a = np.ones(shape=(1, 10))
b = a.reshape((10, ))
c = a.reshape((-1, ))
d = a.flatten()
print(f"a.shape: {a.shape}\n")
print(f"b.shape: {b.shape}")
print(f"c.shape: {c.shape}")
print(f"d.shape: {d.shape}")

a.shape: (1, 10)

b.shape: (10,)
c.shape: (10,)
d.shape: (10,)


In [4]:
import numpy as np
a = np.ones(shape=(10, 1))
b = a.reshape((10, ))
c = a.reshape((-1, ))
d = a.flatten()
print(f"a.shape: {a.shape}\n")
print(f"b.shape: {b.shape}")
print(f"c.shape: {c.shape}")
print(f"d.shape: {d.shape}")

a.shape: (10, 1)

b.shape: (10,)
c.shape: (10,)
d.shape: (10,)


In [10]:
import numpy as np
a = np.ones(shape=(1, 3, 4))
b = np.ones(shape=(3, 4, 1))
c = a.reshape(*a.shape[1:])
d = b.reshape(*b.shape[:-1])
print(f"a.shape: {a.shape}","\n",a)
print(f"b.shape: {b.shape}\n",b)
print(f"c.shape: {c.shape}","\n",c,"\n")
print(f"d.shape: {d.shape}","\n",d)

a.shape: (1, 3, 4) 
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
b.shape: (3, 4, 1)
 [[[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]]
c.shape: (3, 4) 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

d.shape: (3, 4) 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
import numpy as np
a = np.arange(9).reshape((3, 3))

row, col = a[1, :], a[:, 1]
print(f"a.shape: {a.shape}\n",a)
print(f"row.shape: {row.shape}","\n",row,"\n")
print(f"col.shape: {col.shape}","\n",col)

a.shape: (3, 3)
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
row.shape: (3,) 
 [3 4 5] 

col.shape: (3,) 
 [1 4 7]


In [18]:
import numpy as np
a = np.arange(9).reshape((1, -1)) #행으로 flatten
print(a)
b = np.arange(9).reshape((-1, 1)) #열로 flatten
print(b)
c = a[0, :]
d = b[:, 0]

print(f"a.shape: {a.shape}")
print(f"b.shape: {b.shape}\n")
print(f"c.shape: {c.shape}")
print(f"d.shape: {d.shape}")

[[0 1 2 3 4 5 6 7 8]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
a.shape: (1, 9)
b.shape: (9, 1)

c.shape: (9,)
d.shape: (9,)


In [22]:
import numpy as np
a = np.ones(shape=(1, 3, 4))
print(a)
b = np.ones(shape=(3, 4, 1))
c = a[0, ...]   #첫번째 dimension은 0으로 인덱싱하고 나머지는 다 가져오는걸로
print(c)        
d = b[..., 0]   #세번째 dimension은 0으로 인덱싱하고 나머지는 다 가져오는걸로 

print(f"a.shape: {a.shape}")
print(f"b.shape: {b.shape}\n")
print(f"c.shape: {c.shape}")
print(f"d.shape: {d.shape}")


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
a.shape: (1, 3, 4)
b.shape: (3, 4, 1)

c.shape: (3, 4)
d.shape: (3, 4)


In [21]:
import numpy as np
a = np.ones(shape=(1, 3, 4))
c = np.squeeze(a)
d = a.squeeze()
print(f"a.shape: {a.shape}\n")
print(f"c.shape: {c.shape}")
print(f"d.shape: {d.shape}\n")


a.shape: (1, 3, 4)

c.shape: (3, 4)
d.shape: (3, 4)



### 차원 바꾸기

In [26]:
import numpy as np
a = np.random.normal(size=(3, 4, 5, 6))
print(a,"\n")
b = np.swapaxes(a, 0, 1)   # 0번째 차원과 1번째 차원을 바꿔주세요 (3,4,5,6) ---> (4,3,5,6)
c = np.swapaxes(a, 0, 2)
d = np.swapaxes(a, 0, 3)
print(f"a.shape: {a.shape}\n")
print(f"b.shape: {b.shape}")
print(f"c.shape: {c.shape}")
print(f"d.shape: {d.shape}")


[[[[-3.12320712 -2.0408872  -0.7575299  -0.75734289 -0.17620007
    -0.04651948]
   [ 1.92878872 -0.00646705  0.53550923  0.01411465  1.4353138
     1.56675266]
   [-2.0030063   0.07931311  0.87345427  0.4623239  -0.88293685
     0.9604054 ]
   [-0.7595232  -2.0005998   0.59005092  0.70985477 -0.41452226
     1.35276911]
   [ 2.08466379 -1.12150311  1.68153222 -1.2331681   0.78702429
     0.7431335 ]]

  [[ 0.77962106 -1.75436404 -0.62960782 -0.22759251 -1.02055762
     1.01799954]
   [ 0.74303142  0.35137391 -1.42972806  0.68308431 -0.7373042
    -0.77915801]
   [ 0.12319342  0.96197268  1.20050022 -1.27644863 -3.13353721
     1.1238012 ]
   [-0.37456618 -0.62401722 -0.34321403  0.26416757  1.74478737
     0.15722047]
   [ 0.25529466 -1.56805885 -1.23761285 -0.46165266 -0.5280214
    -0.32621148]]

  [[ 0.67913423 -0.42773426 -1.7446644  -0.50491728 -1.54003921
    -1.29433113]
   [-0.35214007  0.35691252  0.84500562 -0.01348388  1.30146538
    -0.1340071 ]
   [ 0.89792275  1.65712012

In [27]:
import numpy as np
a = np.random.normal(size=(3, 200, 100))
b = np.swapaxes(a, 0, -1)
print(f"a.shape: {a.shape}\n")
print(f"b.shape: {b.shape}")


a.shape: (3, 200, 100)

b.shape: (100, 200, 3)


In [28]:
import numpy as np
a = np.random.normal(size=(3, 4, 5, 6))
b = np.moveaxis(a, source=0, destination=1)
c = np.moveaxis(a, source=0, destination=2)
d = np.moveaxis(a, source=0, destination=-1)

print(f"a.shape: {a.shape}\n")
print(f"b.shape: {b.shape}")
print(f"c.shape: {c.shape}")
print(f"d.shape: {d.shape}")


a.shape: (3, 4, 5, 6)

b.shape: (4, 3, 5, 6)
c.shape: (4, 5, 3, 6)
d.shape: (4, 5, 6, 3)


In [29]:
import numpy as np
a = np.random.normal(size=(3, 4, 5, 6))
b = np.moveaxis(a, source=1, destination=0)
c = np.moveaxis(a, source=1, destination=2)
d = np.moveaxis(a, source=1, destination=-1)
print(f"a.shape: {a.shape}\n")
print(f"b.shape: {b.shape}")
print(f"c.shape: {c.shape}")
print(f"d.shape: {d.shape}")


a.shape: (3, 4, 5, 6)

b.shape: (4, 3, 5, 6)
c.shape: (3, 5, 4, 6)
d.shape: (3, 5, 6, 4)


In [30]:
a = np.random.normal(size=(3, 4))
b = np.transpose(a)
c = a.T
print(f"a.shape: {a.shape}\n")
print(f"b.shape: {b.shape}")
print(f"c.shape: {c.shape}")

a.shape: (3, 4)

b.shape: (4, 3)
c.shape: (4, 3)


In [31]:
a = np.random.normal(size=(3, 4, 5, 6, 7))
b = np.transpose(a)
c = a.T
print(f"a.shape: {a.shape}\n")
print(f"b.shape: {b.shape}")
print(f"c.shape: {c.shape}")


a.shape: (3, 4, 5, 6, 7)

b.shape: (7, 6, 5, 4, 3)
c.shape: (7, 6, 5, 4, 3)


In [32]:
import numpy as np
a = np.random.normal(size=(3, 4, 5))
b = np.transpose(a, axes=(0, 1, 2))
c = np.transpose(a, axes=(1, 2, 0))
d = np.transpose(a, axes=(2, 0, 1))
e = np.transpose(a, axes=(2, 1, 0))
print(f"a.shape: {a.shape}\n")
print(f"b.shape: {b.shape}")
print(f"c.shape: {c.shape}")
print(f"d.shape: {d.shape}")
print(f"e.shape: {e.shape}")


a.shape: (3, 4, 5)

b.shape: (3, 4, 5)
c.shape: (4, 5, 3)
d.shape: (5, 3, 4)
e.shape: (5, 4, 3)


In [33]:
import numpy as np
a = np.random.normal(size=(3, 4, 5, 6))
b = np.transpose(a, axes=tuple(range(a.ndim))[::-1])
print(f"a.shape: {a.shape}\n")
print(f"b.shape: {b.shape}")


a.shape: (3, 4, 5, 6)

b.shape: (6, 5, 4, 3)
