In [8]:
import numpy as np
x = np.arange(5)
y = np.arange(2, 6)
X, Y = np.meshgrid(x, y)
Z = X + Y
X, Y, Z = X.T, Y.T, Z.T
print(f"X: \n{X}")
print(f"Y: \n{Y}")
print(f"Z: \n{Z}")



X: 
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
Y: 
[[2 3 4 5]
 [2 3 4 5]
 [2 3 4 5]
 [2 3 4 5]
 [2 3 4 5]]
Z: 
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]]


#### broad cating

In [9]:
import numpy as np
x = np.arange(5)
y = np.arange(2, 6)

X = x.reshape((-1, 1))
Y = y.reshape((1, -1))
Z = X + Y
print(f"X: {X.shape}\n{X}")
print(f"Y: {Y.shape}\n{Y}")
print(f"Z: {Z.shape}\n{Z}")


X: (5, 1)
[[0]
 [1]
 [2]
 [3]
 [4]]
Y: (1, 4)
[[2 3 4 5]]
Z: (5, 4)
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]]


In [11]:
import numpy as np
x = np.arange(5)
y = np.arange(2, 6)
X = x.reshape((-1, 1))
Y = y.reshape((1, -1))
Z = X + Y
print(f"x[0] + y: {Z[0, :]}")
print(f"x[3] + y: {Z[3, :]}\n")
print(f"y[0] + x: {Z[:, 0]}")
print(f"y[2] + x: {Z[:, 2]}")

x[0] + y: [2 3 4 5]
x[3] + y: [5 6 7 8]

y[0] + x: [2 3 4 5 6]
y[2] + x: [4 5 6 7 8]


In [17]:
import numpy as np
X = np.random.uniform(-5, 5, (4, 2))
Y = np.random.uniform(-5, 5, (3, 2))

for x in X:
    for y in Y:
        add = x + y
        print(f"{add}", end=' ')
    print()


[-0.04696392  2.99753369] [-1.92464962 -2.14735594] [-0.09615765 -3.55585008] 
[ 1.7158217  -0.96852767] [-0.161864   -6.11341731] [ 1.66662797 -7.52191145] 
[1.84216961 4.85201223] [-0.0355161  -0.29287741] [ 1.79297588 -1.70137155] 
[5.40773944 2.34257384] [ 3.53005374 -2.80231579] [ 5.35854572 -4.21080993] 


In [20]:
import numpy as np
X = np.random.uniform(-5, 5, (4, 2))
Y = np.random.uniform(-5, 5, (3, 2))

X = np.expand_dims(X, axis=1)
Y = np.expand_dims(Y, axis=0)
Z = X + Y
print("shapes: ")
print(f"X/Y/Z: {X.shape}/{Y.shape}/{Z.shape}\n")   # 3번째 인자는 2이닌깐 무시하고 첫 번째 두번째 Broad cast 되서 z값이 (4,3,2)가됨.

shapes: 
X/Y/Z: (4, 1, 2)/(1, 3, 2)/(4, 3, 2)



In [21]:
import numpy as np
np.set_printoptions(sign='+')
X = np.random.uniform(-5, 5, (4, 2))
Y = np.random.uniform(-5, 5, (3, 2))
X = np.expand_dims(X, axis=1)
Y = np.expand_dims(Y, axis=0)
Z = X + Y

print(f"X[0] + Y: \n{Z[0, :, :]}")
print(f"X[3] + Y: \n{Z[3, :, :]}\n") 
print(f"Y[0] + X: \n{Z[:, 0, :]}")
print(f"Y[2] + X: \n{Z[:, 2, :]}")


X[0] + Y: 
[[+3.98004337 +0.77888992]
 [+3.3887991  +2.3379429 ]
 [+2.78113746 -1.50681404]]
X[3] + Y: 
[[-1.21838787 -4.37508883]
 [-1.80963215 -2.81603585]
 [-2.41729379 -6.66079279]]

Y[0] + X: 
[[+3.98004337 +0.77888992]
 [+2.26508721 -0.60317185]
 [+0.96549279 -5.77262162]
 [-1.21838787 -4.37508883]]
Y[2] + X: 
[[+2.78113746 -1.50681404]
 [+1.06618129 -2.88887581]
 [-0.23341313 -8.05832558]
 [-2.41729379 -6.66079279]]


### Euclidean Distance

In [24]:
import numpy as np
X = np.random.uniform(-5, 5, (4, 2))
Y = np.random.uniform(-5, 5, (3, 2))
print("X > ","\n",X,"\n")
print("Y > ","\n",Y,"\n")
for x in X:
    for y in Y:
        e_dist = np.sqrt(np.sum(np.square(x - y)))
        print(f"{e_dist:5.2f}", end=' ')
    print()

X >  
 [[-0.38210496 -4.64940908]
 [+2.35105    +2.92013136]
 [-2.04276268 -4.17135183]
 [+3.02714439 +1.21982371]] 

Y >  
 [[-2.2401451  -1.9459673 ]
 [+1.71350511 +3.61461879]
 [-2.26502778 -2.78730624]] 

 3.28  8.53  2.65 
 6.69  0.94  7.34 
 2.23  8.64  1.40 
 6.15  2.73  6.64 


In [26]:
import numpy as np
x = np.random.uniform(-5, 5, (4, 2))
y = np.random.uniform(-5, 5, (3, 2))

X = np.expand_dims(x, axis=1)
Y = np.expand_dims(y, axis=0)
Z = np.sqrt(np.sum(np.square(X - Y), axis=-1))
print(Z)

[[+9.46094666 +8.37976849 +5.99949796]
 [+7.41264922 +4.14980553 +2.8639669 ]
 [+1.53951201 +4.65875218 +3.84254112]
 [+2.47767209 +5.96934847 +3.3812171 ]]


In [30]:
print(x,"\n\n",y)

[[+3.91836474 +2.69033578]
 [+2.86128453 -1.56334963]
 [-3.70989434 -2.81494111]
 [-2.71320038 +0.13575075]] 

 [[-4.55126899 -1.52568321]
 [+0.4394565  -4.93316193]
 [+0.01315779 -1.86414931]]


In [33]:
print(X,"\n\n\n",Y)

[[[+3.91836474 +2.69033578]]

 [[+2.86128453 -1.56334963]]

 [[-3.70989434 -2.81494111]]

 [[-2.71320038 +0.13575075]]] 


 [[[-4.55126899 -1.52568321]
  [+0.4394565  -4.93316193]
  [+0.01315779 -1.86414931]]]
